CREATE TABLE IF NOT EXISTS Feedback (
  id SERIAL PRIMARY KEY, 
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  );

CREATE INDEX IF NOT EXISTS idx_feedback_email ON feedback(email);

CREATE INDEX IF NOT EXISTS idx_feedback_created_at ON feedback (created_at DESC);
